name: Update Submodules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 0

      - name: Update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --remote --recursive --force

      - name: Commit and push if there are changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --quiet && exit 0
          git commit -m "Automated submodule update"
          git push
